apiVersion: v1
kind: Service
metadata:
  name: "vllm-cpu"
  labels:
    app: "vllm-cpu"
spec:
  type: "ClusterIP"
  ports:
    - name: vllm-cpu-server
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "vllm-cpu-server"